export const types = {
    FETCH_DEBRIS_CATEGORIES: 'FETCH_DEBRIS_CATEGORIES',
    FETCH_DEBRIS_CATEGORY: 'FETCH_DEBRIS_CATEGORY',
    CREATE_DEBRIS_CATEGORY: 'CREATE_DEBRIS_CATEGORY',
    UPDATE_DEBRIS_CATEGORY: 'UPDATE_DEBRIS_CATEGORY',
    DELETE_DEBRIS_CATEGORY: 'DELETE_DEBRIS_CATEGORY',
};