export const types = {
    FETCH_DEBRIS_TYPES: 'FETCH_DEBRIS_TYPES',
    FETCH_DEBRIS_TYPE: 'FETCH_DEBRIS_TYPE',
    CREATE_DEBRIS_TYPE: 'CREATE_DEBRIS_TYPE',
    UPDATE_DEBRIS_TYPE: 'UPDATE_DEBRIS_TYPE',
    DELETE_DEBRIS_TYPE: 'DELETE_DEBRIS_TYPE',
};