export const types = {
    FETCH_TAXA_LEVELS: 'FETCH_TAXA_LEVELS',
    FETCH_TAXA_LEVEL: 'FETCH_TAXA_LEVEL',
    CREATE_TAXA_LEVEL: 'CREATE_TAXA_LEVEL',
    UPDATE_TAXA_LEVEL: 'UPDATE_TAXA_LEVEL',
    DELETE_TAXA_LEVEL: 'DELETE_TAXA_LEVEL',
    FETCH_TAXA_LEVEL_SELECTOR: 'FETCH_TAXA_LEVEL_SELECTOR'
};