export const types = {
    FETCH_COLLECTIONS: 'FETCH_COLLECTIONS',
    FETCH_COLLECTION: 'FETCH_COLLECTION',
    CREATE_COLLECTION: 'CREATE_COLLECTION',
    UPDATE_COLLECTION: 'UPDATE_COLLECTION',
    DELETE_COLLECTION: 'DELETE_COLLECTION',
    UPDATE_STATE: 'UPDATE_STATE',
    FETCH_SELF_COLLECTIONS: 'FETCH_SELF_COLLECTIONS',
    FETCH_COLLECTIONS_COORDINATES: 'FETCH_COLLECTIONS_COORDINATES',
    SET_CURRENT_STATE: 'SET_CURRENT_STATE',
    FETCH_COLLECTION_GRAPH: 'FETCH_COLLECTION_GRAPH',
    EXPORT_COLLECTION: 'EXPORT_COLLECTION',
    EXPORT_TEMPLATE: 'EXPORT_TEMPLATE'
};