export const types = {
    FETCH_DEBRIS_RUGOSITIES: 'FETCH_DEBRIS_RUGOSITIES',
    FETCH_DEBRIS_RUGOSITY: 'FETCH_DEBRIS_RUGOSITY',
    CREATE_DEBRIS_RUGOSITY: 'CREATE_DEBRIS_RUGOSITY',
    UPDATE_DEBRIS_RUGOSITY: 'UPDATE_DEBRIS_RUGOSITY',
    DELETE_DEBRIS_RUGOSITY: 'DELETE_DEBRIS_RUGOSITY',
    FETCH_DEBRIS_RUGOSITY_SELECTOR: 'FETCH_DEBRIS_RUGOSITY_SELECTOR'
};