export const types = {
    FETCH_TAXA_POPULATION_STATUSES: 'FETCH_TAXA_POPULATION_STATUSES',
    FETCH_TAXA_POPULATION_STATUS: 'FETCH_TAXA_POPULATION_STATUS',
    CREATE_TAXA_POPULATION_STATUS: 'CREATE_TAXA_POPULATION_STATUS',
    UPDATE_TAXA_POPULATION_STATUS: 'UPDATE_TAXA_POPULATION_STATUS',
    DELETE_TAXA_POPULATION_STATUS: 'DELETE_TAXA_POPULATION_STATUS',
};