export const types = {
    FETCH_REPORTS: 'FETCH_REPORTS',
    FETCH_REPORT: 'FETCH_REPORT',
    CREATE_REPORT: 'CREATE_REPORT',
    UPDATE_REPORT: 'UPDATE_REPORT',
    DELETE_REPORT: 'DELETE_REPORT',
    UPDATE_STATE: 'UPDATE_STATE',
    FETCH_SELF_REPORTS: 'FETCH_SELF_REPORTS',
    FETCH_REPORTS_COORDINATES: 'FETCH_REPORTS_COORDINATES',
    SET_CURRENT_STATE: 'SET_CURRENT_STATE',
    FETCH_REPORT_GRAPH: 'FETCH_REPORT_GRAPH',
    EXPORT_REPORTS: 'EXPORT_REPORTS'
};