export const types = {
    FETCH_TAXA_NATIVE_REGIONS: 'FETCH_TAXA_NATIVE_REGIONS',
    FETCH_TAXA_NATIVE_REGION: 'FETCH_TAXA_NATIVE_REGION',
    CREATE_TAXA_NATIVE_REGION: 'CREATE_TAXA_NATIVE_REGION',
    UPDATE_TAXA_NATIVE_REGION: 'UPDATE_TAXA_NATIVE_REGION',
    DELETE_TAXA_NATIVE_REGION: 'DELETE_TAXA_NATIVE_REGION',
    FETCH_TAXA_NATIVE_REGION_SELECTOR: 'FETCH_TAXA_NATIVE_REGION_SELECTOR'
};