export const types = {
    FETCH_DEBRIS_HABITATS: 'FETCH_DEBRIS_HABITATS',
    FETCH_DEBRIS_HABITAT: 'FETCH_DEBRIS_HABITAT',
    CREATE_DEBRIS_HABITAT: 'CREATE_DEBRIS_HABITAT',
    UPDATE_DEBRIS_HABITAT: 'UPDATE_DEBRIS_HABITAT',
    DELETE_DEBRIS_HABITAT: 'DELETE_DEBRIS_HABITAT',
};