export const types = {
    FETCH_TAXA_SPECIES_STATUSES: 'FETCH_TAXA_SPECIES_STATUSES',
    FETCH_TAXA_SPECIES_STATUS: 'FETCH_TAXA_SPECIES_STATUS',
    CREATE_TAXA_SPECIES_STATUS: 'CREATE_TAXA_SPECIES_STATUS',
    UPDATE_TAXA_SPECIES_STATUS: 'UPDATE_TAXA_SPECIES_STATUS',
    DELETE_TAXA_SPECIES_STATUS: 'DELETE_TAXA_SPECIES_STATUS',
    FETCH_TAXA_SPECIES_STATUS_SELECTOR: 'FETCH_TAXA_SPECIES_STATUS_SELECTOR'
};