export const types = {
    FETCH_DEBRIS_MATERIALS: 'FETCH_DEBRIS_MATERIALS',
    FETCH_DEBRIS_MATERIAL: 'FETCH_DEBRIS_MATERIAL',
    CREATE_DEBRIS_MATERIAL: 'CREATE_DEBRIS_MATERIAL',
    UPDATE_DEBRIS_MATERIAL: 'UPDATE_DEBRIS_MATERIAL',
    DELETE_DEBRIS_MATERIAL: 'DELETE_DEBRIS_MATERIAL',
};