export const types = {
    FETCH_DEBRIS_SUB_CATEGORIES: 'FETCH_DEBRIS_SUB_CATEGORIES',
    FETCH_DEBRIS_SUB_CATEGORY: 'FETCH_DEBRIS_SUB_CATEGORY',
    CREATE_DEBRIS_SUB_CATEGORY: 'CREATE_DEBRIS_SUB_CATEGORY',
    UPDATE_DEBRIS_SUB_CATEGORY: 'UPDATE_DEBRIS_SUB_CATEGORY',
    DELETE_DEBRIS_SUB_CATEGORY: 'DELETE_DEBRIS_SUB_CATEGORY',
};