export const types = {
    FETCH_TAXA_MATURITIES: 'FETCH_TAXA_MATURITIES',
    FETCH_TAXA_MATURITY: 'FETCH_TAXA_MATURITY',
    CREATE_TAXA_MATURITY: 'CREATE_TAXA_MATURITY',
    UPDATE_TAXA_MATURITY: 'UPDATE_TAXA_MATURITY',
    DELETE_TAXA_MATURITY: 'DELETE_TAXA_MATURITY',
};