export const types = {
    FETCH_DEBRIS_SIZES: 'FETCH_DEBRIS_SIZES',
    FETCH_DEBRIS_SIZE: 'FETCH_DEBRIS_SIZE',
    CREATE_DEBRIS_SIZE: 'CREATE_DEBRIS_SIZE',
    UPDATE_DEBRIS_SIZE: 'UPDATE_DEBRIS_SIZE',
    DELETE_DEBRIS_SIZE: 'DELETE_DEBRIS_SIZE',
    FETCH_DEBRIS_SIZE_SELECTOR: 'FETCH_DEBRIS_SIZE_SELECTOR'
};