export const types = {
    FETCH_TAXA_ABUNDANCES: 'FETCH_TAXA_ABUNDANCES',
    FETCH_TAXA_ABUNDANCE: 'FETCH_TAXA_ABUNDANCE',
    CREATE_TAXA_ABUNDANCE: 'CREATE_TAXA_ABUNDANCE',
    UPDATE_TAXA_ABUNDANCE: 'UPDATE_TAXA_ABUNDANCE',
    DELETE_TAXA_ABUNDANCE: 'DELETE_TAXA_ABUNDANCE',
    FETCH_TAXA_ABUNDANCE_SELECTOR: 'FETCH_TAXA_ABUNDANCE_SELECTOR'
};