export const types = {
    FETCH_DEBRIS_THICKNESSES: 'FETCH_DEBRIS_THICKNESSES',
    FETCH_DEBRIS_THICKNESS: 'FETCH_DEBRIS_THICKNESS',
    CREATE_DEBRIS_THICKNESS: 'CREATE_DEBRIS_THICKNESS',
    UPDATE_DEBRIS_THICKNESS: 'UPDATE_DEBRIS_THICKNESS',
    DELETE_DEBRIS_THICKNESS: 'DELETE_DEBRIS_THICKNESS',
};