export const types = {
    FETCH_TAXA_VIABILITIES: 'FETCH_TAXA_VIABILITIES',
    FETCH_TAXA_VIABILITY: 'FETCH_TAXA_VIABILITY',
    CREATE_TAXA_VIABILITY: 'CREATE_TAXA_VIABILITY',
    UPDATE_TAXA_VIABILITY: 'UPDATE_TAXA_VIABILITY',
    DELETE_TAXA_VIABILITY: 'DELETE_TAXA_VIABILITY',
    FETCH_TAXA_VIABILITY_SELECTOR: 'FETCH_TAXA_VIABILITY_SELECTOR'
};